name: Build and publish containers

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/Portal/**'
    - '.github/workflows/build-push-container-images.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Log in to ACR
      uses: docker/login-action@v3
      with: 
        registry: bfreg.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/Portal/Dockerfile
        push: true
        tags: |
          bfreg.azurecr.io/portal/portal-web:${{ github.sha }}
          bfreg.azurecr.io/portal/portal-web:latest
          
            

     

